### PR TITLE
[RFR] Simplifiy dashboard collection configuration

### PR DESCRIPTION
**Pull request by fzaninotto**
```js
// before
nga.dashboard().addCollection("posts", nga.collection(post));
// after
nga.dashboard().addCollection(nga.collection(post));
```

Please release 0.7.1 after merge.

### CODE REVIEW

**Comment by jeromemacias** [comment]
Test failed.

By release `0.7.1`, you mean `0.2.1` ?

**Comment by fzaninotto** [comment]
Sorry, tests are now fixed. Yes, I mean 0.2.1.

**Comment by jeromemacias** [comment]
`admin-config` 0.2.1 has just been published.

**Comment by fzaninotto** [comment]
Thanks!

**Pull request merged**
